# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NewDish' do

#    ## TTPL Library
    pod 'TTPLLibrary', :git => 'https://github.com/iosttpl/TTPLLibrary.git'

    pod 'Alamofire'

    pod 'AlamofireObjectMapper'
    
    pod 'SDWebImage', '~> 4.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewDish

end
